/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { Kinds, KindsInterface } from "../../contracts/Kinds";

const _abi = [
  {
    inputs: [],
    name: "COUNTER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FACTORY",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "GOVERNOR",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TIMELOCK",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TOKEN",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61014861003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100615760003560e01c80632dd31000146100665780636dc0ae221461009f5780637aadef8b146100c657806382bfefc8146100ed57806399b7057914610114575b600080fd5b61008d7f547b500e425d72fd0723933cceefc203cef652b4736fd04250c3369b3e1a0a7381565b60405190815260200160405180910390f35b61008d7f1a6838efa4183e08fe3607359d1259272af9d4716f65e1a7b5921f78fd5a3c6a81565b61008d7faefebe170cbaff0af052a32795af0e1b8afff9850f946ad2869be14f3553437181565b61008d7f96706879d29c248edfb2a2563a8a9d571c49634c0f82013e6f5a7cde739d35d481565b61008d7fcfe10320bcac53115bb5d1a7c2626fb69a0bc1509a3149c15a8ece734bc15d548156fea164736f6c6343000818000a";

type KindsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: KindsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Kinds__factory extends ContractFactory {
  constructor(...args: KindsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Kinds & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Kinds__factory {
    return super.connect(runner) as Kinds__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): KindsInterface {
    return new Interface(_abi) as KindsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Kinds {
    return new Contract(address, _abi, runner) as unknown as Kinds;
  }
}
