/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as clock from "./clock";
export type { clock };
export type { BytecodeFactory } from "./BytecodeFactory";
export type { ContractRegistry } from "./ContractRegistry";
export type { Counter } from "./Counter";
export type { CounterFactory } from "./CounterFactory";
export type { ERC20Token } from "./ERC20Token";
export type { IContractRegistry } from "./IContractRegistry";
export type { Kinds } from "./Kinds";
export type { OZGovernor } from "./OZGovernor";
export type { SimpleCounter } from "./SimpleCounter";
export type { TimelockController } from "./TimelockController";
